// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uccjhzudeyjeobxewccn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjY2poenVkZXlqZW9ieGV3Y2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2ODExMzcsImV4cCI6MjA3NDI1NzEzN30.Nu-KVdZJRz3eyFvN_PxlfVKs1yaKh2f77PVHTBA-ZGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});